### ISSUE TITLE
[Feature Request] auto-suggestion endpoint

### ISSUE THREAD

**Issue by sbhal** [vigneshrajj/gofind#4]
An endpoint to provide auto-suggestions for user-created commands in Firefox.

This request is motivated from https://git.mills.io/prologic/golinks

**Comment by vigneshrajj** [comment]
Didn't fully understand the usage. Doesn't the browser already make the suggestions based on what you type? Can you share a screenshot of golinks showing how it works? 

Btw, thank you for providing the link to Golinks. I had once seen it a few years ago and then later I couldn't find it again anywhere as I couldn't remember its name or where it was hosted. That's why I ended up making my own version of it.

**Comment by sbhal** [comment]
This isn't implemented for golinks and that is why I asked in first place. See details at: https://git.mills.io/prologic/golinks/issues/23
Although, I wouldn't put high priority for this feature.

**Comment by vigneshrajj** [comment]
9951b854e1a5e28bbebb665444f25c4e90aa3a02 Firefox autosuggestions live now!
